server:
  port: 4636
spring:
  datasource:
    url: jdbc:mysql://192.168.1.100:3308/center_service?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 100
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
      validation-timeout: 3000
      read-only: false
      login-timeout: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
    open-in-view: false

  rabbitmq:
    #    addresses: 192.168.0.254:5671,192.168.0.254:5673,192.168.0.254:5674
    host: 192.168.1.107
    password: 123456
    username: fecred
    port: 5672
    publisher-returns: true
    publisher-confirm-type: correlated
    template:
      mandatory: true
    virtual-host: saas


xxl:
  job:
    admin:
      ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://192.168.1.109:8080/xxl-job-admin
    ### 执行器通讯TOKEN [选填]
    accessToken:
    executor:
      ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: mq-service-xxl-job
      ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address: http://192.168.1.111:9901
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip: 192.168.1.111
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 9901
    ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: ./data/xxl-job-logs
    ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 2
logging:
  file:
    name: ./logs/rabbitmq-service.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
      file-name-pattern: ./logs/rabbitmq-service.%d{yyyy-MM-dd}.%i.log

project:
  version: @project.version@
